name: "CD: Main Workflow"
run-name: ${{ github.actor }} Deployment Workflow

env:
  VERCEL_TOKEN: ${{ vars.VERCEL_TOKEN }}
  VERCEL_ORG_ID: ${{ vars.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ vars.VERCEL_PROJECT_ID }}
  VERCEL_TOKEN1: ${{ secrets.TEST_SECRET }}
  VERCEL_TOKEN2: ${{ vars.FIRST-NEXTJS-PROJECT.VERCEL_TOKEN }}
  VERCEL_TOKEN3: ${{ secrets.VERCEL_TOKEN }}
  VERCEL_TOKEN4: ${{ secrets.FIRST-NEXTJS-PROJECT.VERCEL_TOKEN }}

on:
  push:
    branches: ["main"]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        env:
          TEST_SECRET: ${{ secrets.TEST_SECRET }}
        run: |
          echo "repository variable 2: $TEST_SECRET2"
      - name: test
        run: |
          echo "echo test"
          echo "repository variable 1: $TEST_SECRET"
          echo "repository variable 2: $TEST_SECRET2"
        env:
          TEST_SECRET: ${{ secrets.TEST_SECRET }}
          TEST_SECRET2: ${{ vars.VERCEL_TOKEN2 }}
