name: "CD: Main Workflow"
run-name: ${{ github.actor }} Deployment Workflow

env:
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  push:
    branches: ["main"]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: test
        run: |
          echo "VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}"
          echo "VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}""
          echo "VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}"

      - name: Run Installation
        run: yarn install

      - name: Run Deploy
        run: yarn deploy
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
