name: "CD: Main Workflow"
run-name: ${{ github.actor }} Deployment Workflow

env:
  VERCEL_TOKEN: ${{ FIRST_NEXTJS_PROJECT.VERCEL_TOKEN }}
  VERCEL_ORG_ID: ${{ FIRST_NEXTJS_PROJECT.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ FIRST_NEXTJS_PROJECT.VERCEL_PROJECT_ID }}

on:
  push:
    branches: ["main"]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Installation
        run: yarn install

      - name: Run Deploy
        run: yarn deploy
        env:
          VERCEL_TOKEN: ${{ FIRST_NEXTJS_PROJECT.VERCEL_TOKEN }}
