name: "CD: Main Workflow"
run-name: ${{ github.actor }} Deployment Workflow

env:
  VERCEL_TOKEN: ${{ vars.VERCEL_TOKEN }}
  VERCEL_ORG_ID: ${{ vars.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ vars.VERCEL_PROJECT_ID }}

on:
  push:
    branches: ["main"]
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ vars.FIRST-NEXTJS-PROJECT }}
    steps:
      - uses: actions/checkout@v4

      - name: test
        run: |
          echo "echo test"
          echo "repository variable : $VERCEL_TOKEN"
        env:
          VERCEL_TOKEN: ${{ vars.VERCEL_TOKEN }}

