name: "CD: Main Workflow"

on:
  push:
    branches: ["main"]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        env:
          TEST_SECRET: ${{ secrets.TEST_SECRET }}
        run: |
          echo "repository variable 2: $TEST_SECRET2"
      - name: test
        run: |
          echo "echo test"
          echo "repository variable 1: $TEST_SECRET"
          echo "repository variable 2: $TEST_SECRET2"
        env:
          TEST_SECRET: ${{ secrets.TEST_SECRET }}
          TEST_SECRET2: ${{ vars.VERCEL_TOKEN2 }}
