name: "CD: Main Workflow"
run-name: ${{ github.actor }} Deployment Workflow

env:
  VERCEL_TOKEN: ${{ vars.VERCEL_TOKEN }}
  VERCEL_ORG_ID: ${{ vars.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ vars.VERCEL_PROJECT_ID }}
  VERCEL_TOKEN1: ${{ secrets.TEST_SECRET }}
  VERCEL_TOKEN2: ${{ vars.FIRST-NEXTJS-PROJECT.VERCEL_TOKEN }}
  VERCEL_TOKEN3: ${{ secrets.VERCEL_TOKEN }}
  VERCEL_TOKEN4: ${{ secrets.FIRST-NEXTJS-PROJECT.VERCEL_TOKEN }}

on:
  push:
    branches: ["main"]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: test
        run: |
          echo "echo test"
          echo "repository variable 1: $VERCEL_TOKEN1"
          echo "repository variable 2: $VERCEL_TOKEN2"
        env:
          VERCEL_TOKEN1: ${{ secrets.TEST_SECRET }}
          VERCEL_TOKEN2: ${{ vars.VERCEL_TOKEN2 }}
