name: "CI: Main Workflow"
run-name: ${{ github.actor }} CI Workflow
on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - "**.js"
  push:
    branches: ["main"]
jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Installation
        run: yarn install

      - name: Run single command
        run: yarn lint
