name: "CI: Main Workflow"
run-name: ${{ github.actor }} CI Workflow

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - "**.js"
  push:
    branches: ["main"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: yarn

      - name: Run Installation
        run: yarn install

      - name: Run Linter
        run: yarn lint

      - name: Run Preview Deployment
        run: yarn deploy:preview
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          GITHUB_PR_NUMBER: ${{github.event.pull_request.number}}
          GITHUB_REPO: 'NextJS-first-project'

      - name: Cypress
        uses: cypress-io/github-action@v6
        with:
          browser: chrome

      - name: Run test
        run: yarn test:e2e


