name: "CI: Main Workflow"
run-name: ${{ github.actor }} Main Workflow
on:
  pull_request:
    types: [open, synchronize]
jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Installation
        run: yarn install

      - name: Run single command
        run: yarn lint
